// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnmbylcodvldlgfmhjjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFubWJ5bGNvZHZsZGxnZm1oampoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MjExMzUsImV4cCI6MjA2MDE5NzEzNX0.eAkrUid-KCCSE2dsWlfQbnV6FvlUmQk9UusV_tAx1lY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);